name: dmdave.net S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
    steps:
        - uses: actions/checkout@v4

        - name: Set AWS Creds
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-west-2
            role-to-assume: arn:aws:iam::108626704866:role/dmdave_github_update

        - name: Deploy to S3
          run: aws s3 sync . dmdave.net --delete --exclude '.git*'
          
